title: "dataset models are trained on" # Title for the resulting plot.  
line_extent: 0.15 # extent of identity line to draw on your plot. 
models: ## all of the model information you want to plot. 
  ResNet18: ## Name of the first model to plot. 
    modelnames: ## List of all of filepaths where model predictions are stored (h5 files for imagenet, .npy files for cifar10.) Should be given relative to `scripts` directory. 
      - modelpath1
      - modelpath2
    labelpaths: ## Optional: list of all filepaths where labels are stored (only required for cifar10.)   
      - labelpath1
      - labelpath2

  

