"model1":
  - robust_results11-17-21_01:19.42_base_googlenet 
  - robust_results11-17-21_02:53.46_base_googlenet  
  - robust_results11-17-21_04:27.55_base_googlenet  
  - robust_results11-17-21_06:02.07_base_googlenet  
"model2":   
  - robust_results11-13-21_01:28.26_base_wideresnet18_4
  - robust_results11-13-21_03:38.44_base_wideresnet18_4  
  - robust_results11-13-21_05:49.19_base_wideresnet18_4  
  - robust_results11-13-21_07:59.30_base_wideresnet18_4
"metric": BrierScore 
"metricshowname": "Brier Score"  
"oodname": ood_ 
"basemodel":   
  - robust_results11-15-21_02:46.11_base_resnet18
"thresh_score": 0.01    
"dumpname": avg_avg  
"select": 0  
"indshowname": "CIFAR10"  
"oodshowname": "CIFAR10.1"  
"model1showname": "Avg GoogleNet - Single ResNet 18"
"model2showname": "Avg. WideResNet 18-4 - Single ResNet 18"  
