"model1":
  - robust_results12-02-21_05:39.49_base_wideresnet18 
  - robust_results12-02-21_05:40.12_base_wideresnet18
  - robust_results12-02-21_05:40.35_base_wideresnet18  
  - robust_results12-02-21_05:40.58_base_wideresnet18  
"model2":   
  - robust_results12-02-21_05:42.05_base_wideresnet18_4
  - robust_results12-02-21_05:42.50_base_wideresnet18_4  
  - robust_results12-02-21_05:43.35_base_wideresnet18_4  
  - robust_results12-02-21_05:44.20_base_wideresnet18_4
"basemodel":   
  - robust_results12-02-21_05:34.26_base_vgg11_bn
"metric": Likelihood 
"metricshowname": Likelihood  
"oodname": ood_cinic_ 
"thresh_score": 0.01    
"dumpname": avg_avg  
"select": 0  
"indshowname": "CIFAR10"  
"oodshowname": "CINIC10"  
"model1showname": "Avg. WideResNet 18-2 - Single VGG-11"
"model2showname": "Avg. WideResNet 18-4 - Single VGG-11"  
